# Generated by Django 5.1 on 2024-08-16 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='colection/', verbose_name='Изображения')),
                ('name', models.CharField(max_length=15, verbose_name='Названия катигории')),
            ],
            options={
                'verbose_name': 'Kатигория',
                'verbose_name_plural': 'Kатигории',
            },
        ),
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Фото')),
                ('created', models.PositiveBigIntegerField(default=0, verbose_name='Созданно')),
                ('nfts_sold', models.PositiveBigIntegerField(default=0, verbose_name='Проданно')),
                ('balans', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс')),
                ('follow', models.PositiveIntegerField(default=0, verbose_name='Подписки')),
                ('follow_my', models.PositiveIntegerField(default=0, verbose_name='Подпищики')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('name', models.CharField(max_length=15, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описания')),
                ('prise', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_sold', models.BooleanField(verbose_name='Продаётся')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='marketplace.category', verbose_name='Катигория')),
                ('tegs', models.ManyToManyField(to='marketplace.tegs', verbose_name='Теги')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='marketplace.usermodel', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Nft',
                'verbose_name_plural': 'Nft',
            },
        ),
    ]
