# Generated by Django 5.1 on 2024-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='follow_my',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default='img/user_1.png', upload_to='photo/', verbose_name='Фото'),
        ),
    ]
