# Generated by Django 5.1 on 2024-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_usermodel_follow_remove_usermodel_follow_my_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='is_sold',
            field=models.BooleanField(default=True, verbose_name='Продаётся'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default='img/user_1.png', upload_to='photo', verbose_name='Фото'),
        ),
    ]
