# Generated by Django 5.1 on 2024-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_nft_is_sold_alter_usermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nfts_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Проданно'),
        ),
    ]
